### ISSUE TITLE
Перезаписывается progress у ордеред-меты

### ISSUE THREAD

**Issue by spyderdfx** [abak-press/resque-integration#76]
Мета [здесь](https://github.com/abak-press/resque-integration/blob/master/lib/resque/integration/ordered.rb#L115) не релодится, и при вызове `finish!` прогресс [перезаписывается](https://github.com/lmarlow/resque-meta/blob/b117efe6c2eec437a1df9c3584fc74ca85f2578c/lib/resque/plugins/meta/metadata.rb#L61) значениями, которые были изначально.
Ломает прогрессбар - по завершению будет `0/1 0%` вместо записанного ранее прогресса.

В resque-meta реализовано [after-хуком](https://github.com/lmarlow/resque-meta/blob/b117efe6c2eec437a1df9c3584fc74ca85f2578c/lib/resque/plugins/meta.rb#L106)

**Comment by TamarinEA** [comment]
https://github.com/abak-press/resque-integration/pull/151
